- hosts: mayl_home
  become: true
  roles:
    - { role: base, tags: ['base'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: imap, tags: ['imap'] }
    - { role: ollama, tags: ['ollama'] }
    - { role: processor, tags: ['processor'] }
    - { role: dashboard, tags: ['dashboard'] }
